const fiatCurrencies = [
   { value:"AFN", label:"Afghan afghani"},
   { value:"ALL", label:"Albanian lek"  },
   { value:"DZD", label:"Algerian dinar"  },
   { value:"AOA", label:"Angolan kwanza"  },
   { value:"ARS", label:"Argentine peso"  },
   { value:"AMD", label:"Armenian dram"  },
   { value:"AWG", label:"Aruban florin"  },
   { value:"AUD", label:"Australian dollar"  },
   { value:"AZN", label:"Azerbaijani manat"  },
   { value:"BHD", label:"Bahraini dinar"  },
   { value:"BSD", label:"Bahamian dollar"  },
   { value:"BDT", label:"Bangladeshi taka"  },
   { value:"BBD", label:"Barbadian dollar"  },
   { value:"BYN", label:"Belarusian ruble"  },
   { value:"BZD", label:"Belize dollar"  },
   { value:"BMD", label:"Bermudian dollar"  },
   { value:"BTN", label:"Bhutanese ngultrum"  },
   { value:"BOB", label:"Bolivian boliviano"  },
   { value:"BAM", label:"Bosnia and Herzegovina convertible mark"  },
   { value:"BWP", label:"Botswana pula"  },
   { value:"BRL", label:"Brazilian real"  },
   { value:"GBP", label:"British pound"  },
   { value:"BND", label:"Brunei dollar"  },
   { value:"MMK", label:"Burmese kyat"  },
   { value:"BIF", label:"Burundian franc"  },
   { value:"KHR", label:"Cambodian riel"  },
   { value:"CAD", label:"Canadian dollar"  },
   { value:"CVE", label:"Cape Verdean escudo"  },
   { value:"KYD", label:"Cayman Islands dollar"  },
   { value:"XAF", label:"Central African CFA franc"  },
   { value:"XPF", label:"CFP franc"  },
   { value:"CLP", label:"Chilean peso"  },
   { value:"CNY", label:"Chinese yuan"  },
   { value:"COP", label:"Colombian peso"  },
   { value:"KMF", label:"Comorian franc"  },
   { value:"CDF", label:"Congolese franc"  },
   { value:"CRC", label:"Costa Rican colón"  },
   { value:"HRK", label:"Croatian kuna"  },
   { value:"CUC", label:"Cuban convertible peso"  },
   { value:"CUP", label:"Cuban peso"  },
   { value:"CZK", label:"Czech koruna"  },
   { value:"DKK", label:"Danish krone"  },
   { value:"DOP", label:"Dominican peso"  },
   { value:"DJF", label:"Djiboutian franc"  },
   { value:"XCD", label:"Eastern Caribbean dollar"  },
   { value:"EGP", label:"Egyptian pound"  },
   { value:"ERN", label:"Eritrean nakfa"  },
   { value:"ETB", label:"Ethiopian birr"  },
   { value:"EUR", label:"Euro"  },
   { value:"FKP", label:"Falkland Islands pound"  },
   { value:"FJD", label:"Fijian dollar"  },
   { value:"GMD", label:"Gambian dalasi"  },
   { value:"GEL", label:"Georgian lari"  },
   { value:"GHS", label:"Ghanaian cedi"  },
   { value:"GIP", label:"Gibraltar pound"  },
   { value:"GTQ", label:"Guatemalan quetzal"  },
   { value:"GGP", label:"Guernsey pound"  },
   { value:"GNF", label:"Guinean franc"  },
   { value:"GYD", label:"Guyanese dollar"  },
   { value:"HTG", label:"Haitian gourde"  },
   { value:"HNL", label:"Honduran lempira"  },
   { value:"HKD", label:"Hong Kong dollar"  },
   { value:"HUF", label:"Hungarian forint"  },
   { value:"ISK", label:"Icelandic króna"  },
   { value:"INR", label:"Indian rupee"  },
   { value:"IDR", label:"Indonesian rupiah"  },
   { value:"IRR", label:"Iranian rial"  },
   { value:"IQD", label:"Iraqi dinar"  },
   { value:"ILS", label:"Israeli new shekel"  },
   { value:"JMD", label:"Jamaican dollar"  },
   { value:"JPY", label:"Japanese yen"  },
   { value:"JEP", label:"Jersey pound"  },
   { value:"JOD", label:"Jordanian dinar"  },
   { value:"KZT", label:"Kazakhstani tenge"  },
   { value:"KES", label:"Kenyan shilling"  },
   { value:"KID", label:"Kiribati dollar"  },
   { value:"KGS", label:"Kyrgyzstani som"  },
   { value:"KWD", label:"Kuwaiti dinar"  },
   { value:"LAK", label:"Lao kip"  },
   { value:"LBP", label:"Lebanese pound"  },
   { value:"LSL", label:"Lesotho loti"  },
   { value:"LRD", label:"Liberian dollar"  },
   { value:"LYD", label:"Libyan dinar"  },
   { value:"MOP", label:"Macanese pataca"  },
   { value:"MKD", label:"Macedonian denar"  },
   { value:"MGA", label:"Malagasy ariary"  },
   { value:"MWK", label:"Malawian kwacha"  },
   { value:"MYR", label:"Malaysian ringgit"  },
   { value:"MVR", label:"Maldivian rufiyaa"  },
   { value:"IMP", label:"Manx pound"  },
   { value:"MRU", label:"Mauritanian ouguiya"  },
   { value:"MUR", label:"Mauritian rupee"  },
   { value:"MXN", label:"Mexican peso"  },
   { value:"MDL", label:"Moldovan leu"  },
   { value:"MNT", label:"Mongolian tögrög"  },
   { value:"MAD", label:"Moroccan dirham"  },
   { value:"MZN", label:"Mozambican metical"  },
   { value:"NAD", label:"Namibian dollar"  },
   { value:"NPR", label:"Nepalese rupee"  },
   { value:"ANG", label:"Netherlands Antillean guilder"  },
   { value:"TWD", label:"New Taiwan dollar"  },
   { value:"NZD", label:"New Zealand dollar"  },
   { value:"NIO", label:"Nicaraguan córdoba"  },
   { value:"NGN", label:"Nigerian naira"  },
   { value:"KPW", label:"North Korean won"  },
   { value:"NOK", label:"Norwegian krone"  },
   { value:"OMR", label:"Omani rial"  },
   { value:"PKR", label:"Pakistani rupee"  },
   { value:"PAB", label:"Panamanian balboa"  },
   { value:"PGK", label:"Papua New Guinean kina"  },
   { value:"PYG", label:"Paraguayan guaraní"  },
   { value:"PEN", label:"Peruvian sol"  },
   { value:"PHP", label:"Philippine peso"  },
   { value:"PLN", label:"Polish złoty"  },
   { value:"QAR", label:"Qatari riyal"  },
   { value:"RON", label:"Romanian leu"  },
   { value:"RUB", label:"Russian ruble"  },
   { value:"RWF", label:"Rwandan franc"  },
   { value:"SHP", label:"Saint Helena pound"  },
   { value:"WST", label:"Samoan tālā"  },
   { value:"STN", label:"São Tomé and Príncipe dobra"  },
   { value:"SAR", label:"Saudi riyal"  },
   { value:"RSD", label:"Serbian dinar"  },
   { value:"SLL", label:"Sierra Leonean leone"  },
   { value:"SGD", label:"Singapore dollar"  },
   { value:"SOS", label:"Somali shilling"  },
   { value:"SLS", label:"Somaliland shilling"  },
   { value:"ZAR", label:"South African rand"  },
   { value:"KRW", label:"South Korean won"  },
   { value:"SSP", label:"South Sudanese pound"  },
   { value:"SRD", label:"Surinamese dollar"  },
   { value:"SEK", label:"Swedish krona"  },
   { value:"CHF", label:"Swiss franc"  },
   { value:"LKR", label:"Sri Lankan rupee"  },
   { value:"SZL", label:"Swazi lilangeni"  },
   { value:"SYP", label:"Syrian pound"  },
   { value:"TJS", label:"Tajikistani somoni"  },
   { value:"TZS", label:"Tanzanian shilling"  },
   { value:"THB", label:"Thai baht"  },
   { value:"TOP", label:"Tongan paʻanga"  },
   { value:"PRB", label:"Transnistrian ruble"  },
   { value:"TTD", label:"Trinidad and Tobago dollar"  },
   { value:"TND", label:"Tunisian dinar"  },
   { value:"TRY", label:"Turkish lira"  },
   { value:"TMT", label:"Turkmenistan manat"  },
   { value:"TVD", label:"Tuvaluan dollar"  },
   { value:"UGX", label:"Ugandan shilling"  },
   { value:"UAH", label:"Ukrainian hryvnia"  },
   { value:"AED", label:"United Arab Emirates dirham"  },
   { value:"USD", label:"United States dollar"  },
   { value:"UYU", label:"Uruguayan peso"  },
   { value:"UZS", label:"Uzbekistani soʻm"  },
   { value:"VUV", label:"Vanuatu vatu"  },
   { value:"VES", label:"Venezuelan bolívar soberano"  },
   { value:"VND", label:"Vietnamese đồng"  },
   { value:"XOF", label:"West African CFA franc"  },
   { value:"ZMW", label:"Zambian kwacha"  },
   { value:"ZWB", label:"Zimbabwean bonds"  },
]